{% set name = "RotamerConvolveMD" %}
{% set version = "1.3.2" %}
{% set sha256 = "d8122a19d4eee224e969fd7edc61338f24346928679a0ccd0898cf237b59cb4d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mdanalysis>=0.16.2
    - numpy

test:
  imports:
    - rotcon

about:
  home: https://github.com/MDAnalysis/RotamerConvolveMD
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Analysis of protein MD trajectories or conformational ensembles in terms of DEER of PRE spin-label distances
  description: |
    This package analyses molecular dynamics trajectories or conformational ensembles in terms
    of spin-label distances as probed in double electron-electron resonance (DEER) experiments 
    and spin-label to amide protin distances as probed in paramagnetic relaxation enhancement 
    (PRE) experiments. The spin labels are fitted on trajectories and the spin label mobility
    is taken into account using a rotamer library.
  doc_url: https://www.mdanalysis.org/RotamerConvolveMD
  dev_url: https://github.com/MDAnalysis/RotamerConvolveMD

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
