{% set name = "RotamerConvolveMD" %}
{% set version = "1.3.0" %}
{% set sha256 = "dd94b16224ba915fe38bdbffe1cf90275ffa1ae248f2729ce84ce110dce70d1d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py3k or win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - mdanalysis
    - numpy

test:
  imports:
    - rotcon

about:
  home: https://github.com/MDAnalysis/RotamerConvolveMD
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
      This package analyses molecular dynamics trajectories or conformational ensembles in terms
      of spin-label distances as probed in double electron-electron resonance (DEER) experiments 
      and spin-label to amide protin distances as probed in paramagnetic relaxation enhancement 
      (PRE) experiments. The spin labels are fitted on trajectories and the spin label mobility
      is taken into account using a rotamer library.

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
