travis:
  secure:
    BINSTAR_TOKEN: TclGoipQ6N6jFvKckbBFec3dc5RuW6m29WE+OSgSXgLjF5XAcgHW0mgpCuO8IsSl+WJ5go0I5EC5/W/cwcfvVKuJGXDl5Jc5IAcgb1LRYI+3yIQIxkeFMuQ4INVtAo+YFJtCg5Q60e9g+949AVLMkqGaDkIY/HO2dYbH4LnP2dIWaFTIAvYYaafnDtM14rS1LCwfM3RHkKESJjFmqCYT4fnqH6Y3Y3H0Yl6DznCTORyQRt6G164IfchSKW56wEtQORYB/6u+BVhmEzqZ5J5flj+NBWpxkiEdIt76PoT8MaYEw2Brpao1U8f7l4dIIHPWx3t0kzoGjBZVQcCg4lmpsO9JfYJGE+6MaGQtiF84GuNN4KRzHidNsGcRxtTOUvxvvkKjH2M/Lv6xSdU6vwORoxm5u1c96E6nOOe469AgsqGWEZsygzEh6qGjYYit98M3BBO0kW1Jz+QnrpI+Gl0xEaeYEjCXMrUGGObDY1WB46PR2n0pQI++7muIer4ZBzDSI6VH5cVkFsW16ILstrZnvwE84Hb0VX1NO0E/AJzbDAW+UE6RDa11VroZKVgDfzB92o9Q4Ha1E6hLOrcxWX8sbPKOp5TH+XzsEWy1P4PGs3IkoED0gkAGKW5siRPI+Yi2xTCU5eeGVdC699NIzjzi5516YNz+VD4fbNRQrKXFL9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
